#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

mfx_reject_option_in_args \
    "--check-scope" \
    "run-posix-core-effects-contract-regression.sh enforces --check-scope effects; do not pass --check-scope" \
    "$@"

export MFX_TEST_EFFECTS_DURATION_SCALE="${MFX_TEST_EFFECTS_DURATION_SCALE:-0.5}"
export MFX_TEST_EFFECTS_SIZE_SCALE="${MFX_TEST_EFFECTS_SIZE_SCALE:-1.2}"
export MFX_TEST_EFFECTS_OPACITY_SCALE="${MFX_TEST_EFFECTS_OPACITY_SCALE:-0.78}"
export MFX_TEST_EFFECTS_TRAIL_THROTTLE_SCALE="${MFX_TEST_EFFECTS_TRAIL_THROTTLE_SCALE:-0.6}"

export MFX_EXPECT_EFFECTS_DURATION_SCALE="${MFX_EXPECT_EFFECTS_DURATION_SCALE:-$MFX_TEST_EFFECTS_DURATION_SCALE}"
export MFX_EXPECT_EFFECTS_SIZE_SCALE="${MFX_EXPECT_EFFECTS_SIZE_SCALE:-$MFX_TEST_EFFECTS_SIZE_SCALE}"
export MFX_EXPECT_EFFECTS_OPACITY_SCALE="${MFX_EXPECT_EFFECTS_OPACITY_SCALE:-$MFX_TEST_EFFECTS_OPACITY_SCALE}"
export MFX_EXPECT_EFFECTS_TRAIL_THROTTLE_SCALE="${MFX_EXPECT_EFFECTS_TRAIL_THROTTLE_SCALE:-$MFX_TEST_EFFECTS_TRAIL_THROTTLE_SCALE}"

exec "$SCRIPT_DIR/run-posix-core-automation-contract-regression.sh" --check-scope effects "$@"
